version: "3"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    tty: true
    volumes:
      - ./:/app
    ports:
      - "80:80"
    command: cargo run